### PR TITLE
Set locale appropriately

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Like https://github.com/elm-lang/elm-make/pull/83.

### CODE REVIEW

**Comment by kirikaza** [comment]
This PR hangs for more than year just because of misconfiguration on CI.
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-repl-0.16 (user goal)
rejecting: elm-repl-0.16:!test (global constraint requires opposite flag
selection)
```
Could we fix it?

**Comment by jvoigtlaender** [comment]
Who tells you that the sole reason this is not getting merged is the CI failure?

**Comment by kirikaza** [comment]
Let me explain what it looks like: PR is neither applied, nor discarded, nor commented somehow. Surely, I could be mistaken, but I see this PR as forgotten.

**Comment by evancz** [comment]
Since this PR was given, we started using @process-bot to help explain how things work here. The bot always says:

> Thanks for the issue! Make sure it satisfies [this checklist][checklist]. My human colleagues will appreciate it!
>
> Here is [what to expect next][expectations], and if anyone wants to comment, keep [these things][participation] in mind.

[checklist]: https://github.com/process-bot/contribution-checklist/blob/master/issues.md
[expectations]: https://github.com/process-bot/contribution-checklist/blob/master/expectations.md
[participation]: https://github.com/process-bot/contribution-checklist/blob/master/participation.md

One of the important aspects is called "batching" and it is explained in [this talk](https://youtu.be/DSjbTC-hvqQ?t=18m55s).

Due to some changes in the structure of the compiler, it will ultimately not make sense to merge this in. Fine. Now the question is, should I close the issue on *your* schedule or on *my* schedule? Is it better for the Elm ecosystem for me to run from issue to issue, getting yelled at by strangers, or does it make sense to do concentrated and coherent chunks of work? The talk I linked above tries to explain the choices I have made here, and I'm sorry you found those choices frustrating.

**Pull request closed without merging**
